name: Corrective
analytics: {}
github: true
author: {}
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/6844d35d-f6b0-4149-bf48-dccecc3a0846.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/6844d35d-f6b0-4149-bf48-dccecc3a0846.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
layout_spectrum: 0.02446749
color:
  lightness: 0.8928044
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  saturation: 0.1765376
  brandStrength: 0.1379462
  rhythmicContrast: 0.6216332
content_rating:
  adult: false
typography_spectrum: 0.9980282
opengraph: {}
title: ''
description: A unique approach to health and fitness
